name: erp
version: "3.8"
services:
  ms-iam:
    container_name: ms-iam
    build: .
    restart: always
    ports:
      - "8080:8080"
    networks:
      - mysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/blendtecnologia_ms-iam?allowPublicKeyRetrieval=true
    depends_on:
      - mysql
    volumes:
      - ./:/opt/ms-iam/

  mysql:
    container_name: mysql
    image: "mysql"
    restart: always
    ports:
      - "3306:3306"
    networks:
      - mysql-net
    environment:
      MYSQL_DATABASE: blendtecnologia_ms-iam
      MYSQL_ROOT_PASSWORD: 123456
networks:
  mysql-net: